(function() {var implementors = {};
implementors['byteorder'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>&gt; for <a class='enum' href='byteorder/enum.Error.html' title='byteorder::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='byteorder/enum.Error.html' title='byteorder::Error'>Error</a>&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>",];implementors['libc'] = [];implementors['yaqb'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.NulError.html' title='std::ffi::c_str::NulError'>NulError</a>&gt; for <a class='enum' href='yaqb/result/enum.ConnectionError.html' title='yaqb::result::ConnectionError'>ConnectionError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.NulError.html' title='std::ffi::c_str::NulError'>NulError</a>&gt; for <a class='enum' href='yaqb/result/enum.Error.html' title='yaqb::result::Error'>Error</a>","impl&lt;E&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='yaqb/result/enum.Error.html' title='yaqb::result::Error'>Error</a>&gt; for <a class='enum' href='yaqb/result/enum.TransactionError.html' title='yaqb::result::TransactionError'>TransactionError</a>&lt;E&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='yaqb/result/enum.TransactionError.html' title='yaqb::result::TransactionError'>TransactionError</a>&lt;<a class='enum' href='yaqb/result/enum.Error.html' title='yaqb::result::Error'>Error</a>&gt;&gt; for <a class='enum' href='yaqb/result/enum.Error.html' title='yaqb::result::Error'>Error</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
